services:
  mysql:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql
    container_name: mysql_db
    restart: always
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_VIRTUAL_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis
    container_name: redis_cache
    restart: always
    ports:
      - "${REDIS_LOCAL_PORT}:${REDIS_VIRTUAL_PORT}"
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/data
  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - ${RABBITMQ_SERVICE_PORT}:${RABBITMQ_SERVICE_PORT}
      - ${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq_lib:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  

volumes:
  mysql_data:
  redis_data:
  rabbitmq_lib:
    driver: local
  rabbitmq_log:
    driver: local